REAL_COURT_KP = {
    "TOP_LEFT": [0, 0], 
    "TOP_LEFT_HASH": [833, 0],
    "TOP_MID": [1400, 0],
    "TOP_RIGHT_HASH": [1967, 0],
    "TOP_RIGHT": [2800, 0],

    "RIGHT_FT_TOP_RIGHT": [2800, 505],
    "RIGHT_FT_TOP_LEFT": [2220, 505],
    "RIGHT_FT_BOTTOM_LEFT": [2220, 995],
    "RIGHT_FT_BOTTOM_RIGHT": [2800, 995],
    
    "BOTTOM_RIGHT": [2800, 1500],
    "BOTTOM_RIGHT_HASH": [1967, 1500],
    "BOTTOM_MID": [1400, 1500],
    "BOTTOM_LEFT_HASH": [833, 1500],
    "BOTTOM_LEFT": [0, 1500],
    
    "LEFT_FT_BOTTOM_LEFT": [0, 995],
    "LEFT_FT_BOTTOM_RIGHT": [580, 995],
    "LEFT_FT_TOP_RIGHT": [580, 505],
    "LEFT_FT_TOP_LEFT": [0, 505],

    "CENTER_TOP": [1400, 570],
    "CENTER_BOTTOM": [1400, 930],
}

COURT_DIMENSIONS = {
    "SIDELINE": 28.0,
    "BASELINE": 15.0,
    "CENTER": 3.6,
    "FT_SIDE": 5.8,
    "FT_BASE": 4.9
}

LINES = {
    "CENTER_LINE": ["TOP_MID", "CENTER_TOP", "CENTER_BOTTOM", "BOTTOM_MID"],
    "LEFT_BASELINE": ["TOP_LEFT", "LEFT_FT_TOP_LEFT", "LEFT_FT_BOTTOM_LEFT", "BOTTOM_LEFT"],
    "RIGHT_BASELINE": ["TOP_RIGHT", "RIGHT_FT_TOP_RIGHT", "RIGHT_FT_BOTTOM_RIGHT", "BOTTOM_RIGHT"],
    "LEFT_FT": ["TOP_LEFT_HASH", "LEFT_FT_TOP_RIGHT", "LEFT_FT_BOTTOM_RIGHT", "BOTTOM_LEFT_HASH"],
    "RIGHT_FT": ["TOP_RIGHT_HASH", "RIGHT_FT_TOP_LEFT", "RIGHT_FT_BOTTOM_LEFT", "BOTTOM_RIGHT_HASH"],
    "TOP_SIDELINE": ["TOP_LEFT", "TOP_LEFT_HASH", "TOP_MID", "TOP_RIGHT_HASH", "TOP_RIGHT"],
    "BOTTOM_SIDELINE": ["BOTTOM_LEFT", "BOTTOM_LEFT_HASH", "BOTTOM_MID", "BOTTOM_RIGHT_HASH", "BOTTOM_RIGHT"],
}

CROSSES = {
    "TOP_RIGHT": ["RIGHT_BASELINE", "TOP_SIDELINE"],
    "BOTTOM_RIGHT": ["RIGHT_BASELINE", "BOTTOM_SIDELINE"],
    "TOP_LEFT": ["LEFT_BASELINE", "TOP_SIDELINE"],
    "BOTTOM_LEFT": ["LEFT_BASELINE", "BOTTOM_SIDELINE"],
    "TOP_MID": ["CENTER_LINE", "TOP_SIDELINE"],
    "BOTTOM_MID": ["CENTER_LINE", "BOTTOM_SIDELINE"],
    # "BOTTOM_LEFT_HASH": ["LEFT_FT", "BOTTOM_SIDELINE"],
    # "BOTTOM_RIGHT_HASH": ["RIGHT_FT", "BOTTOM_SIDELINE"],
    # "TOP_LEFT_HASH": ["LEFT_FT", "TOP_SIDELINE"],
    # "TOP_RIGHT_HASH": ["RIGHT_FT", "TOP_SIDELINE"],
}